### ISSUE TITLE
How to train GPRO on 2 GPUs, one for training, one for vllm

### ISSUE THREAD

**Issue by AIR-hl** [huggingface/trl#2864]
### Reproduction

When I use `Qwen2.5-3B-instruct` to train GRPO, the device for vllm always appear OOM when loading weights. II used two GPUs with 32GB of memory, one device for training, another for vllm. I dont know why a 3B model using so much memory on `device 1`

![Image](https://github.com/user-attachments/assets/79dfd03c-d123-496d-9fcc-07afc3027dff)

arguments settings:
```yaml
per_device_train_batch_size: 8
gradient_accumulation_steps: 8
num_generations: 8
use_vllm: true
vllm_gpu_memory_utilization: 0.8
use_peft: true
lora_r: 64
lora_alpha: 64
load_in_4bit: true
use_bnb_nested_quant: true
attn_implementation: flash_attention_2
bf16: true
...
```

Start command:
```shell
export CUDA_VISIBLE_DEVICES=0,1
accelerate launch --num_processes 1 train_Datawhale-R1.py --config Datawhale-R1.yaml
```

### System Info

- Platform: Linux-5.15.0-78-generic-x86_64-with-glibc2.35
- Python version: 3.10.8
- PyTorch version: 2.5.1
- CUDA device(s): NVIDIA vGPU-32GB, NVIDIA vGPU-32GB
- Transformers version: 4.48.3
- Accelerate version: 1.3.0
- Accelerate config: not found
- Datasets version: 3.1.0
- HF Hub version: 0.27.0
- TRL version: 0.16.0.dev0+ffcb9f4
- bitsandbytes version: 0.45.2
- DeepSpeed version: 0.16.3
- Diffusers version: 0.32.2
- Liger-Kernel version: not installed
- LLM-Blender version: not installed
- OpenAI version: 1.59.7
- PEFT version: 0.14.0

### Checklist

- [x] I have checked that my issue isn't already filed (see [open issues](https://github.com/huggingface/trl/issues?q=is%3Aissue))
- [x] I have included my system information
- [x] Any code provided is minimal, complete, and reproducible ([more on MREs](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks))
- [x] Any code provided is properly formatted in code blocks, (no screenshot, [more on code blocks](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks))
- [x] Any traceback provided is complete

**Comment by MohamedAliRashad** [comment]
I have the same problem and i am using an 80GB GPU, how i am getting an OOM with such a small model ?

**Comment by zhzLuke96** [comment]
me too, OOM in `3b` model... Confusing

**Comment by leonardtang** [comment]
+1!

**Comment by Maghoumi** [comment]
See this [blog](https://www.philschmid.de/mini-deepseek-r1) to use a dedicated GPU for vLLM and use other GPUs for training

TLDR; run with `accelerate` with N-1 processes and don't forget to manually set `vllm_device='cuda:N'`.

**Comment by leonardtang** [comment]
I have 2 GPUs, and unfortunately running `accelerate launch --num_processes=0 train.py` and setting `vllm_device="cuda:1"` doesn't change the memory usage at all.

**Comment by Maghoumi** [comment]
Shouldn't that be `--num_processes=1`? Also, I did `pip install --upgrade git+https://github.com/huggingface/trl.git` on a fresh docker image based on `pytorch/pytorch:2.5.1-cuda12.4-cudnn9-devel` and it works for me.

**Comment by AIR-hl** [comment]
> Shouldn't that be `--num_processes=1`? Also, I did `pip install --upgrade git+https://github.com/huggingface/trl.git` on a fresh docker image based on `pytorch/pytorch:2.5.1-cuda12.4-cudnn9-devel` and it works for me.

Hi! I upgraded `trl` to the latest branch, but the `vllm` still appear OOM on device 1. I used a 3B model with lora and it can works well with unsloth on single GPU. When I reduce `vllm_gpu_memory_utilization` to 0.5, OOM was solved, but new error is here now

![Image](https://github.com/user-attachments/assets/208c60e8-a484-4190-8281-be0633aff668)

It seems that related to `bitandbbytes`, then I cancelled `qlora` and used `lora` instead, but OOM again. 
Anw, It's abnormal for a 3B model to experience OOM when inferring with `lora` and `vllm` on a GPU with 32GB of memory.

Part of my settings
```yaml
use_peft: true
lora_r: 64
lora_alpha: 64
# load_in_4bit: true
# use_bnb_nested_quant: true

use_vllm: true
vllm_device: cuda:1
vllm_gpu_memory_utilization: 0.8

torch_dtype: bfloat16
per_device_train_batch_size: 8
gradient_accumulation_steps: 8
num_generations: 8
```

```shell
export CUDA_VISIBLE_DEVICES=0,1
accelerate launch --num_processes 1 train_r1.py --config r1.yaml
```
