### ISSUE TITLE
tensor shape error occurs when training with GRPO and use_vllm = False

### ISSUE THREAD

**Issue by Saturnoul** [huggingface/trl#2878]
### Reproduction

I'm trying to follow the work of Datawhale-R1, which is a reproduction of Deepseek-R1. The train process is going well when I trained with ```use_vllm=true```, but I got a error of tensor shape mismatching after I set ```use_vllm=false```
```python
# https://github.com/datawhalechina/unlock-deepseek/tree/main/Datawhale-R1/train_Datawhale-R1.py
...
 trainer = GRPOTrainer(
        model=model_args.model_name_or_path,
       
        reward_funcs=[
            format_reward_func, 
            equation_reward_func,
        ],
        args=training_args,
        train_dataset=train_dataset,
        eval_dataset=test_dataset,
        callbacks=callbacks,
    )

trainer.train()
...

```

Accelerate config
```yaml
compute_environment: LOCAL_MACHINE
debug: false
deepspeed_config:
  deepspeed_multinode_launcher: standard
  offload_optimizer_device: none
  offload_param_device: none
  zero3_init_flag: true
  zero3_save_16bit_model: true
  zero_stage: 3
distributed_type: DEEPSPEED
downcast_bf16: 'no'
machine_rank: 0
main_training_function: main
mixed_precision: bf16
num_machines: 1
num_processes: 7
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false
```

TRL config
```yaml
# model config
model_name_or_path: /root/model/Qwen/Qwen2.5-3B-Instruct
model_revision: main
torch_dtype: bfloat16
attn_implementation: flash_attention_2
bf16: true
tf32: true
output_dir: /root/nas/Datawhale-R1

# dataset config
dataset_id_or_path: /root/dataset/Jiayi-Pan/Countdown-Tasks-3to4

# trainer config
max_steps: 450
per_device_train_batch_size: 1
gradient_accumulation_steps: 8
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
learning_rate: 5.0e-7 
lr_scheduler_type: cosine 
warmup_ratio: 0.03 
seed: 2025 

# GRPO config
beta: 0.001 
max_prompt_length: 256
max_completion_length: 4096 
num_generations: 6
use_vllm: false 
vllm_device: cuda:7 
vllm_gpu_memory_utilization: 0.5

# Logging arguments
logging_strategy: steps
logging_steps: 1
save_strategy: "steps"
save_steps: 50 
```

outputs:

```
`use_cache=True` is incompatible with gradient checkpointing. Setting `use_cache=False`.
`use_cache=True` is incompatible with gradient checkpointing. Setting `use_cache=False`.
`use_cache=True` is incompatible with gradient checkpointing. Setting `use_cache=False`.
`use_cache=True` is incompatible with gradient checkpointing. Setting `use_cache=False`.
`use_cache=True` is incompatible with gradient checkpointing. Setting `use_cache=False`.
`use_cache=True` is incompatible with gradient checkpointing. Setting `use_cache=False`.
`use_cache=True` is incompatible with gradient checkpointing. Setting `use_cache=False`.
[rank6]: Traceback (most recent call last):
[rank6]:   File "/root/code/unlock-deepseek/Datawhale-R1/train_Datawhale-R1.py", line 321, in <module>
[rank6]:     main()
[rank6]:   File "/root/code/unlock-deepseek/Datawhale-R1/train_Datawhale-R1.py", line 318, in main
[rank6]:     grpo_function(model_args, dataset_args, training_args, callbacks=callbacks)
[rank6]:   File "/root/code/unlock-deepseek/Datawhale-R1/train_Datawhale-R1.py", line 276, in grpo_function
[rank6]:     train_result = trainer.train(resume_from_checkpoint=last_checkpoint)
[rank6]:   File "/usr/local/lib/python3.10/dist-packages/transformers/trainer.py", line 2171, in train
[rank6]:     return inner_training_loop(
[rank6]:   File "/usr/local/lib/python3.10/dist-packages/transformers/trainer.py", line 2531, in _inner_training_loop
[rank6]:     tr_loss_step = self.training_step(model, inputs, num_items_in_batch)
[rank6]:   File "/usr/local/lib/python3.10/dist-packages/transformers/trainer.py", line 3675, in training_step
[rank6]:     loss = self.compute_loss(model, inputs, num_items_in_batch=num_items_in_batch)
[rank6]:   File "/usr/local/lib/python3.10/dist-packages/trl/trainer/grpo_trainer.py", line 422, in compute_loss
[rank6]:     prompt_completion_ids = unwrapped_model.generate(
[rank6]:   File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 116, in decorate_context
[rank6]:     return func(*args, **kwargs)
[rank6]:   File "/usr/local/lib/python3.10/dist-packages/transformers/generation/utils.py", line 2255, in generate
[rank6]:     result = self._sample(
[rank6]:   File "/usr/local/lib/python3.10/dist-packages/transformers/generation/utils.py", line 3257, in _sample
[rank6]:     outputs = model_forward(**model_inputs, return_dict=True)
[rank6]:   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
[rank6]:     return self._call_impl(*args, **kwargs)
[rank6]:   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1844, in _call_impl
[rank6]:     return inner()
[rank6]:   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1790, in inner
[rank6]:     result = forward_call(*args, **kwargs)
[rank6]:   File "/usr/local/lib/python3.10/dist-packages/transformers/models/qwen2/modeling_qwen2.py", line 816, in forward
[rank6]:     outputs = self.model(
[rank6]:   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
[rank6]:     return self._call_impl(*args, **kwargs)
[rank6]:   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1747, in _call_impl
[rank6]:     return forward_call(*args, **kwargs)
[rank6]:   File "/usr/local/lib/python3.10/dist-packages/transformers/models/qwen2/modeling_qwen2.py", line 562, in forward
[rank6]:     layer_outputs = self._gradient_checkpointing_func(
[rank6]:   File "/usr/local/lib/python3.10/dist-packages/torch/_compile.py", line 32, in inner
[rank6]:     return disable_fn(*args, **kwargs)
[rank6]:   File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/eval_frame.py", line 632, in _fn
[rank6]:     return fn(*args, **kwargs)
[rank6]:   File "/usr/local/lib/python3.10/dist-packages/torch/utils/checkpoint.py", line 496, in checkpoint
[rank6]:     ret = function(*args, **kwargs)
[rank6]:   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
[rank6]:     return self._call_impl(*args, **kwargs)
[rank6]:   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1747, in _call_impl
[rank6]:     return forward_call(*args, **kwargs)
[rank6]:   File "/usr/local/lib/python3.10/dist-packages/transformers/models/qwen2/modeling_qwen2.py", line 259, in forward
[rank6]:     hidden_states, self_attn_weights = self.self_attn(
[rank6]:   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
[rank6]:     return self._call_impl(*args, **kwargs)
[rank6]:   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1747, in _call_impl
[rank6]:     return forward_call(*args, **kwargs)
[rank6]:   File "/usr/local/lib/python3.10/dist-packages/transformers/models/qwen2/modeling_qwen2.py", line 166, in forward
[rank6]:     query_states, key_states = apply_rotary_pos_emb(query_states, key_states, cos, sin)
[rank6]:   File "/usr/local/lib/python3.10/dist-packages/transformers/models/qwen2/modeling_qwen2.py", line 89, in apply_rotary_pos_emb
[rank6]:     q_embed = (q * cos) + (rotate_half(q) * sin)
[rank6]: RuntimeError: The size of tensor a (485) must match the size of tensor b (486) at non-singleton dimension 2
W0217 03:01:09.622000 566 torch/distributed/elastic/multiprocessing/api.py:897] Sending process 631 closing signal SIGTERM
W0217 03:01:09.623000 566 torch/distributed/elastic/multiprocessing/api.py:897] Sending process 632 closing signal SIGTERM
W0217 03:01:09.624000 566 torch/distributed/elastic/multiprocessing/api.py:897] Sending process 633 closing signal SIGTERM
W0217 03:01:09.624000 566 torch/distributed/elastic/multiprocessing/api.py:897] Sending process 634 closing signal SIGTERM
W0217 03:01:09.625000 566 torch/distributed/elastic/multiprocessing/api.py:897] Sending process 635 closing signal SIGTERM
W0217 03:01:09.625000 566 torch/distributed/elastic/multiprocessing/api.py:897] Sending process 636 closing signal SIGTERM
E0217 03:01:10.592000 566 torch/distributed/elastic/multiprocessing/api.py:869] failed (exitcode: 1) local_rank: 6 (pid: 637) of binary: /usr/bin/python3
Traceback (most recent call last):
  File "/usr/local/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/accelerate_cli.py", line 48, in main
    args.func(args)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/launch.py", line 1157, in launch_command
    deepspeed_launcher(args)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/launch.py", line 845, in deepspeed_launcher
    distrib_run.run(args)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/run.py", line 910, in run
    elastic_launch(
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/launcher/api.py", line 138, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/launcher/api.py", line 269, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
train_Datawhale-R1.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2025-02-17_03:01:09
  host      : dlc1ow8x6vzzym3t-master-0
  rank      : 6 (local_rank: 6)
  exitcode  : 1 (pid: 637)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
```

### System Info

- Platform: Linux-5.10.134-008.12.kangaroo.al8.x86_64-x86_64-with-glibc2.35
- Python version: 3.10.12
- PyTorch version: 2.5.1
- CUDA device(s): NVIDIA A100-SXM4-80GB, NVIDIA A100-SXM4-80GB, NVIDIA A100-SXM4-80GB, NVIDIA A100-SXM4-80GB, NVIDIA A100-SXM4-80GB, NVIDIA A100-SXM4-80GB, NVIDIA A100-SXM4-80GB, NVIDIA A100-SXM4-80GB
- Transformers version: 4.48.1
- Accelerate version: 1.3.0
- Accelerate config: not found
- Datasets version: 3.1.0
- HF Hub version: 0.28.1
- TRL version: 0.14.0
- bitsandbytes version: 0.45.1
- DeepSpeed version: 0.15.4
- Diffusers version: not installed
- Liger-Kernel version: not installed
- LLM-Blender version: not installed
- OpenAI version: 1.61.0
- PEFT version: 0.14.0

### Checklist

- [x] I have checked that my issue isn't already filed (see [open issues](https://github.com/huggingface/trl/issues?q=is%3Aissue))
- [x] I have included my system information
- [x] Any code provided is minimal, complete, and reproducible ([more on MREs](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks))
- [x] Any code provided is properly formatted in code blocks, (no screenshot, [more on code blocks](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks))
- [x] Any traceback provided is complete
