### ISSUE TITLE
[GRPO Trainer] NCCL communication timeout when training on multiple machines with deepspeed zero2 config

### ISSUE THREAD

**Issue by Saturnoul** [huggingface/trl#3119]
### Reproduction

# Train Code
[open_r1 grpo.py](https://github.com/huggingface/open-r1/blob/main/src/open_r1/grpo.py)

# Accelerate Config
```yaml
compute_environment: LOCAL_MACHINE
debug: false
deepspeed_config:
  deepspeed_multinode_launcher: standard
  offload_optimizer_device: none
  offload_param_device: none
  zero3_init_flag: false
  zero_stage: 2
distributed_type: DEEPSPEED
downcast_bf16: 'no'
machine_rank: 0
main_training_function: main
mixed_precision: bf16
num_machines: 6
num_processes: 42
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false
```

# GRPO Config
[config_demo.py](https://github.com/huggingface/open-r1/blob/main/recipes/Qwen2.5-1.5B-Instruct/grpo/config_demo.yaml)

# Outputs:
```
[rank45]: torch.distributed.DistBackendError: [45] is setting up NCCL communicator and retrieving ncclUniqueId from [0] via c10d key-value store by key '0', but store->get('0') got error: wait timeout after 1800000ms, keys: //worker/attempt_0/default_pg/0//1//cuda//0
[rank45]: Exception raised from doWait at ../torch/csrc/distributed/c10d/TCPStore.cpp:600 (most recent call first):、
```

### System Info

- Platform: Linux-5.10.134-008.12.kangaroo.al8.x86_64-x86_64-with-glibc2.35
- Python version: 3.10.12
- PyTorch version: 2.5.1
- CUDA device(s): NVIDIA A100-SXM4-80GB, NVIDIA A100-SXM4-80GB, NVIDIA A100-SXM4-80GB, NVIDIA A100-SXM4-80GB, NVIDIA A100-SXM4-80GB, NVIDIA A100-SXM4-80GB, NVIDIA A100-SXM4-80GB, NVIDIA A100-SXM4-80GB
- Transformers version: 4.48.1
- Accelerate version: 1.3.0
- Accelerate config: not found
- Datasets version: 3.1.0
- HF Hub version: 0.28.1
- TRL version: 0.14.0
- bitsandbytes version: 0.45.1
- DeepSpeed version: 0.15.4
- Diffusers version: not installed
- Liger-Kernel version: not installed
- LLM-Blender version: not installed
- OpenAI version: 1.61.0
- PEFT version: 0.14.0

### Checklist

- [x] I have checked that my issue isn't already filed (see [open issues](https://github.com/huggingface/trl/issues?q=is%3Aissue))
- [x] I have included my system information
- [x] Any code provided is minimal, complete, and reproducible ([more on MREs](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks))
- [x] Any code provided is properly formatted in code blocks, (no screenshot, [more on code blocks](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks))
- [x] Any traceback provided is complete
