### ISSUE TITLE
FSDP 2 + DPO Error:  'MixedPrecisionPolicy' object has no attribute '_module_classes_to_ignore'

### ISSUE THREAD

**Issue by JVP15** [huggingface/trl#3581]
### Reproduction

I'm trying to do DPO on 8 GPUs using FSDP and I keep running into an issue when running the offical DPO script w/ my FSDP config. I'm running:

```bash
accelerate launch --config_file fsdp_config.yaml dpo.py \
    --model_name_or_path Qwen/Qwen2-0.5B-Instruct \
    --dataset_name trl-lib/ultrafeedback_binarized \
    --num_train_epochs 1 \
    --logging_steps 25 \
    --output_dir Qwen2-0.5B-DPO
```

Where `dpo.py` is the official example at [trl/scripts/dpo.py](https://github.com/huggingface/trl/blob/main/trl/scripts/dpo.py) and `fsdp_config.yaml` is:

```yaml
compute_environment: LOCAL_MACHINE
debug: false
distributed_type: FSDP
downcast_bf16: 'no'
enable_cpu_affinity: false
fsdp_config:
  fsdp_activation_checkpointing: false
  fsdp_auto_wrap_policy: TRANSFORMER_BASED_WRAP
  fsdp_cpu_ram_efficient_loading: true
  fsdp_offload_params: false
  fsdp_reshard_after_forward: true
  fsdp_state_dict_type: SHARDED_STATE_DICT
  fsdp_version: 2
machine_rank: 0
main_training_function: main
mixed_precision: bf16
num_machines: 1
num_processes: 8
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false
```

Here is the error traceback (repeated across all GPUs) 

```
[rank7]: Traceback (most recent call last):
[rank7]:   File "/mnt/aged-glade/home/****/dpo.py", line 159, in <module>
[rank7]:     main(script_args, training_args, model_args)
[rank7]:   File "/mnt/aged-glade/home/****/dpo.py", line 124, in main
[rank7]:     trainer = DPOTrainer(
[rank7]:               ^^^^^^^^^^^
[rank7]:   File "/mnt/aged-glade/home/****/.conda/envs/hf/lib/python3.12/site-packages/trl/trainer/dpo_trainer.py", line 487, in __init__
[rank7]:     self.ref_model = prepare_fsdp(self.ref_model, self.accelerator)
[rank7]:                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank7]:   File "/mnt/aged-glade/home/****/.conda/envs/hf/lib/python3.12/site-packages/trl/models/utils.py", line 289, in prepare_fsdp
[rank7]:     model = FSDP(model, **kwargs)
[rank7]:             ^^^^^^^^^^^^^^^^^^^^^
[rank7]:   File "/mnt/aged-glade/home/****/.conda/envs/hf/lib/python3.12/site-packages/torch/distributed/fsdp/fully_sharded_data_parallel.py", line 473, in __init__
[rank7]:     _auto_wrap(
[rank7]:   File "/mnt/aged-glade/home/****/.conda/envs/hf/lib/python3.12/site-packages/torch/distributed/fsdp/_wrap_utils.py", line 87, in _auto_wrap
[rank7]:     root_module, mixed_precision._module_classes_to_ignore
[rank7]:                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank7]: AttributeError: 'MixedPrecisionPolicy' object has no attribute '_module_classes_to_ignore'
```

### System Info

- Platform: Linux-6.5.13-65-650-4141-22041-coreweave-amd64-85c45edc-x86_64-with-glibc2.35
- Python version: 3.12.11
- TRL version: 0.19.0.dev0
- PyTorch version: 2.7.1
- accelerator(s): NVIDIA H100 80GB HBM3, NVIDIA H100 80GB HBM3, NVIDIA H100 80GB HBM3, NVIDIA H100 80GB HBM3, NVIDIA H100 80GB HBM3, NVIDIA H100 80GB HBM3, NVIDIA H100 80GB HBM3, NVIDIA H100 80GB HBM3
- Transformers version: 4.52.4
- Accelerate version: 1.7.0
- Accelerate config: not found
- Datasets version: 3.6.0
- HF Hub version: 0.32.4
- bitsandbytes version: not installed
- DeepSpeed version: 0.17.0
- Diffusers version: not installed
- Liger-Kernel version: 0.5.10
- LLM-Blender version: not installed
- OpenAI version: 1.84.0
- PEFT version: not installed
- vLLM version: 0.9.0.1

### Checklist

- [x] I have checked that my issue isn't already filed (see [open issues](https://github.com/huggingface/trl/issues?q=is%3Aissue))
- [x] I have included my system information
- [x] Any code provided is minimal, complete, and reproducible ([more on MREs](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks))
- [x] Any code provided is properly formatted in code blocks, (no screenshot, [more on code blocks](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks))
- [x] Any traceback provided is complete
