### ISSUE TITLE
NEFTune failed when using accelerate

### ISSUE THREAD

**Issue by SingL3** [huggingface/trl#923]
I have launch a training mission on 2 nodes of A100 80G with the following config:
```yaml
compute_environment: LOCAL_MACHINE                                                                                             
debug: false                                                                                                                   
distributed_type: FSDP
downcast_bf16: 'no'
fsdp_config:
  fsdp_auto_wrap_policy: TRANSFORMER_BASED_WRAP
  fsdp_backward_prefetch_policy: BACKWARD_PRE
  fsdp_forward_prefetch: true
  fsdp_offload_params: false
  fsdp_sharding_strategy: 1
  fsdp_state_dict_type: SHARDED_STATE_DICT
  fsdp_sync_module_states: true
  fsdp_use_orig_params: true
machine_rank: 0
main_training_function: main
mixed_precision: 'bf16'
num_machines: 1
num_processes: 8
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false
```
```bash
LAUNCHER="accelerate launch \
    --config_file configs/fsdp_config.yaml \
    --main_process_ip $MASTER_ADDR \
    --main_process_port $MASTER_PORT \
    --machine_rank $RANK \
    --num_processes $NUM_PROCESSES \
    --num_machines $NNODES \
```
Trainer:
```python
from typing import Optional, Union, Callable, Dict, List, Tuple
from functools import wraps

import torch
import torch.nn as nn
from torch.utils.data import Dataset

from transformers import (
        Trainer,
        PreTrainedModel,
        TrainingArguments,
        DataCollator,
        PreTrainedTokenizerBase,
        TrainerCallback,
        EvalPrediction
    )
from peft import PeftModel

def neftune_post_forward_hook(module, input, output):
    """
    Implements the NEFTune forward pass for the model using forward hooks. Note this works only for
    torch.nn.Embedding layers. This method is slightly adapted from the original source code
    that can be found here: https://github.com/neelsjain/NEFTune
    Simply add it to your model as follows:
    ```python
    model = ...
    model.embed_tokens.neftune_noise_alpha = 0.1
    model.embed_tokens.register_forward_hook(neftune_post_forward_hook)
    ```
    Args:
        module (`torch.nn.Module`):
            The embedding module where the hook is attached. Note that you need to set
            `module.neftune_noise_alpha` to the desired noise alpha value.
        input (`torch.Tensor`):
            The input tensor to the model.
        output (`torch.Tensor`):
            The output tensor of the model (i.e. the embeddings).
    """
    if module.training:
        dims = torch.tensor(output.size(1) * output.size(2))
        mag_norm = module.neftune_noise_alpha / torch.sqrt(dims)
        output = output + torch.zeros_like(output).uniform_(-mag_norm, mag_norm)
    return output

class SFTTrainer_NE(Trainer):
    def __init__(
            self,
            model: Union[PreTrainedModel, nn.Module] = None,
            args: TrainingArguments = None,
            data_collator: Optional[DataCollator] = None,
            train_dataset: Optional[Dataset] = None,
            eval_dataset: Optional[Union[Dataset, Dict[str, Dataset]]] = None,
            tokenizer: Optional[PreTrainedTokenizerBase] = None,
            model_init: Optional[Callable[[], PreTrainedModel]] = None,
            compute_metrics: Optional[Callable[[EvalPrediction], Dict]] = None,
            callbacks: Optional[List[TrainerCallback]] = None,
            optimizers: Tuple[torch.optim.Optimizer, torch.optim.lr_scheduler.LambdaLR] = (None, None),
            preprocess_logits_for_metrics: Optional[Callable[[torch.Tensor, torch.Tensor], torch.Tensor]] = None,
            neftune_noise_alpha: Optional[float] = None,
        ):
        self.neftune_noise_alpha = neftune_noise_alpha

        super().__init__(
            model=model,
            args=args,
            data_collator=data_collator,
            train_dataset=train_dataset,
            eval_dataset=eval_dataset,
            tokenizer=tokenizer,
            model_init=model_init,
            compute_metrics=compute_metrics,
            callbacks=callbacks,
            optimizers=optimizers,
            preprocess_logits_for_metrics=preprocess_logits_for_metrics,
        )

    @wraps(Trainer.train)
    def train(self, *args, **kwargs):
        # Activate neftune right before training.
        if self.neftune_noise_alpha is not None:
            self.model = self._activate_neftune(self.model)
        
        output = super().train(*args, **kwargs)

        # After training we make sure to retrieve back the original forward pass method
        # for the embedding layer by removing the forward post hook.
        if self.neftune_noise_alpha is not None:
            if isinstance(self.model, PreTrainedModel):
                embeddings = self.model.get_input_embeddings()
            elif isinstance(self.model, PeftModel):
                embeddings = self.model.base_model.get_input_embeddings()

            self.neftune_hook_handle.remove()
            del embeddings.neftune_noise_alpha

        return output

    def _activate_neftune(self, model):
        r"""
        Activates the neftune as presented in this code: https://github.com/neelsjain/NEFTune and paper: https://arxiv.org/abs/2310.05914
        """
        if isinstance(model, PreTrainedModel):
            embeddings = model.get_input_embeddings()
        elif isinstance(model, PeftModel):
            embeddings = model.base_model.get_input_embeddings()

        embeddings.neftune_noise_alpha = self.neftune_noise_alpha
        hook_handle = embeddings.register_forward_hook(neftune_post_forward_hook)
        self.neftune_hook_handle = hook_handle
        return model
```
After `output = super().train(*args, **kwargs)`, I got this error:
```
[32mpt-vlnq2dtu-master-0 logs:[0m   File "/mnt/home/xxxxxxxxx/rlhf/LLMFinetune/llmft/trainers/sft_trainer_neftune.py", line 117, in train
[32mpt-vlnq2dtu-master-0 logs:[0m     trainer.train(resume_from_checkpoint=resume_from_checkpoint)
[32mpt-vlnq2dtu-master-0 logs:[0m   File "/mnt/home/xxxxxxxxx/rlhf/LLMFinetune/llmft/trainers/sft_trainer_neftune.py", line 117, in train
[32mpt-vlnq2dtu-master-0 logs:[0m   File "/mnt/home/xxxxxxxxx/rlhf/LLMFinetune/llmft/trainers/sft_trainer_neftune.py", line 117, in train
[32mpt-vlnq2dtu-master-0 logs:[0m         
[32mpt-vlnq2dtu-master-0 logs:[0m 
[32mpt-vlnq2dtu-master-0 logs:[0m UnboundLocalError: UnboundLocalError        local variable 'embeddings' referenced before assignment   
```
